import { Injectable, SecurityContext, effect, inject } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { api } from './api';
import { ComponentDef, renderSection } from './engine/render';
import { escapeHtml } from './engine/template';
import { LandingPage, Website } from './models';
import { PageStore } from './page-store';
import { withSharedSections } from './shared-sections';
import { ProjectService, pageDir } from './project.service';
import { siteRuntime } from './site-runtime';
import { SiteService } from './site.service';
import { pageCustomCss, resolveTheme, themeVars } from './styles';
import { WebsiteStore } from './website-store';

/**
 * Script shipped with exported pages. It's the same runtime the editor uses
 * (carousels, mobile menu, animations, forms), serialised from its source.
 */
function runtimeJs(): string {
  return `// Generated by the CMS: carousels, mobile menu, entrance animations, forms, back to top and FAQ accordions.
(() => {
  const rt = (${siteRuntime.toString()})();
  const boot = () => {
    rt.initCarousels(document, { editor: false });
    rt.initNav(document);
    rt.initImageFallback(document);
    rt.initAnimations(document);
    rt.initForms(document, document.documentElement.dataset.formEndpoint || '');
    rt.initBackToTop(document);
    rt.initAccordions(document);
    rt.initTabs(document);
    rt.initMiniHeader(document);
    rt.initAccessibility(document);
  };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();
})();
`;
}

const EXPORT_DELAY_MS = 1500;

/**
 * Builds a static version of every published website into site/dist/:
 *   dist/<website>/index.html            homepage
 *   dist/<website>/<path>/index.html     other pages (nested like the page tree)
 *   dist/assets/site.css, runtime.js     shared CSS and behaviour
 * plus the project's assets and scripts (copied by the server). Links between pages
 * are relative, so the output works from any folder or domain. Rebuilt after saves.
 */
@Injectable({ providedIn: 'root' })
export class Exporter {
  private readonly store = inject(PageStore);
  private readonly websites = inject(WebsiteStore);
  private readonly site = inject(SiteService);
  private readonly project = inject(ProjectService);
  private readonly sanitizer = inject(DomSanitizer);
  private timer: ReturnType<typeof setTimeout> | undefined;

  constructor() {
    effect(() => {
      // Read both signals before testing them so the effect depends on each.
      const pageSaved = this.store.lastSaved();
      const siteSaved = this.websites.lastSaved();
      if (!pageSaved && !siteSaved) return;
      clearTimeout(this.timer);
      this.timer = setTimeout(() => void this.build().catch(() => {}), EXPORT_DELAY_MS);
    });
  }

  /** Renders every published website and writes the result to site/dist/. */
  async build(): Promise<{ pages: number; dir: string }> {
    const components = this.project.components();
    const files: { path: string; content: string }[] = [];
    const tree: { path: string }[] = await api('GET', '/api/files');
    const has = (p: string) => tree.some((f) => f.path === p);
    const published = this.websites.websites().filter((w) => w.status === 'published');
    const scripts: { site: string; slug: string; dir: string }[] = [];
    let count = 0;

    files.push({ path: 'assets/site.css', content: this.siteCss(components) });
    files.push({ path: 'assets/runtime.js', content: runtimeJs() });
    for (const website of published) {
      for (const page of this.store.pagesOf(website.slug)) {
        const segs = this.site.segments(website.slug, page.slug);
        const dir = [website.slug, ...segs].join('/');
        const hasPageJs = has(`${pageDir(website.slug, page.slug)}/page.js`);
        if (hasPageJs) scripts.push({ site: website.slug, slug: page.slug, dir });
        files.push({ path: `${dir}/index.html`, content: this.pageHtml(website, page, components, hasPageJs, has('scripts/main.js')) });
        count++;
      }
    }
    files.push({ path: 'index.html', content: this.indexHtml(published) });

    const res = await api<{ dir: string }>('POST', '/api/export', { files, clean: true, pages: scripts });
    return { pages: count, dir: res.dir };
  }

  private siteCss(components: ComponentDef[]): string {
    const parts = [`/* Generated from site/styles/base.css and site/components/*/component.css — edit those files, not this one. */`, this.project.baseCss()];
    for (const c of components) if (c.css.trim()) parts.push(`/* ${c.folder} */\n${c.css}`);
    return parts.join('\n\n');
  }

  pageHtml(website: Website, page: LandingPage, components: ComponentDef[], hasPageJs: boolean, hasMainJs: boolean): string {
    const byType = new Map(components.map((c) => [c.type, c]));
    const from = this.site.segments(website.slug, page.slug);
    // dist/<site>/<segs…>/index.html → dist root is one level above the website folder.
    const root = '../'.repeat(from.length + 1);
    const link = (slug: string, hash = '') => SiteService.relativeLink(from, this.site.segments(website.slug, slug), hash);
    const opts = {
      editor: false,
      clean: true,
      assetBase: root,
      sanitizeHtml: (html: string) => this.sanitizer.sanitize(SecurityContext.HTML, html) ?? '',
      resolveLink: (slug: string, hash: string) => (this.store.getBySlug(website.slug, slug) ? link(slug, hash) : '#'),
      vars: {
        menu: this.site.menu(website.slug, page.slug, (slug) => link(slug)),
        homeHref: link(website.homepage ?? page.slug),
      },
    };
    const body = withSharedSections(page, this.store.pagesOf(website.slug)).sections
      .filter((s) => s.visible)
      .map((s) => renderSection(s, byType.get(s.type), opts))
      .join('\n');
    const theme = resolveTheme(page.theme);
    const vars = Object.entries(themeVars(page.theme))
      .map(([k, v]) => `${k}: ${v}`)
      .join('; ');
    const fonts = [...new Set([theme.headingFont, theme.fontFamily])]
      .map((f) => `family=${encodeURIComponent(f)}:wght@400;500;600;700;800`)
      .join('&');
    const custom = pageCustomCss(page, '[data-lp="page"]', website.customCss);
    const endpoint = this.project.config().export?.formEndpoint ?? '';
    const title = page.seo.metaTitle || (website.homepage === page.slug ? website.name : `${page.title} · ${website.name}`);

    return `<!doctype html>
<html lang="en"${endpoint ? ` data-form-endpoint="${escapeHtml(endpoint)}"` : ''}>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(title)}</title>
  ${page.seo.metaDescription ? `<meta name="description" content="${escapeHtml(page.seo.metaDescription)}" />` : ''}
  <!-- Generated from site/${pageDir(website.slug, page.slug)}/ — edit it in the CMS or in those files, not here. -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?${fonts}&display=swap" />
  <link rel="stylesheet" href="${root}assets/site.css" />
  ${custom ? `<style>\n${custom}\n  </style>` : ''}
</head>
<body style="margin: 0">
  <div class="lp" data-lp="page" style="${escapeHtml(vars)}">
${body}
  </div>
  <script src="${root}assets/runtime.js" defer></script>
  ${hasMainJs ? `<script src="${root}scripts/main.js" defer></script>` : ''}
  ${hasPageJs ? '<script src="page.js" defer></script>' : ''}
</body>
</html>
`;
  }

  private indexHtml(websites: Website[]): string {
    const links = websites.map((w) => `    <li><a href="${escapeHtml(w.slug)}/">${escapeHtml(w.name)}</a></li>`).join('\n');
    return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(this.project.config().name ?? 'Websites')}</title>
  <style>body { font: 16px/1.6 system-ui, sans-serif; max-width: 640px; margin: 64px auto; padding: 0 16px; }</style>
</head>
<body>
  <h1>${escapeHtml(this.project.config().name ?? 'Websites')}</h1>
  <ul>
${links || '    <li>No published websites yet.</li>'}
  </ul>
</body>
</html>
`;
  }
}
